name: MoonLakeSkinme
main: com.minecraft.moonlake.skinme.SkinmePlugin
version: 1.1.5
author: Month_Light
website: http://www.mcyszh.net
depend: [MoonLake]
commands:
  mlskinme:
    descrption: 月色之湖皮肤插件命令管理
    usage: /<command> help